export enum internalErrorCodes{
    INTERNAL_ERROR = 'INTERNAL_ERROR',
    SCHEMA_VALIDATION_ERROR = 'SCHEMA_VALIDATION_ERROR',
    VALIDATION_ERROR = 'VALIDATION_ERROR',
    CONFLICT_ERROR = 'CONFLICT_ERROR',
    NOT_FOUND_ERROR =  'NOT_FOUND_ERROR',
    AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR',
    FORBIDDEN_ERROR = 'FORBINDDEN_ERROR',
}